version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html

  mysql:
    image: mysql:8.0.20
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: php_app_db
      MYSQL_USER: php_learner
      MYSQL_PASSWORD: php_app
    volumes:
      - ./mysql/data:/var/lib/mysql 
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_php_app
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=php_learner
      - PMA_PASSWORD=php_app
    links:
      - mysql
    ports:
      - 8888:80
